# Generated by Django 4.0.4 on 2024-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lec_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lec_name', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=20)),
                ('lec_level', models.IntegerField(default=0)),
                ('liberal_arts', models.BooleanField(default=True)),
                ('lec_room', models.CharField(max_length=20)),
                ('lec_quota', models.IntegerField()),
                ('credit', models.IntegerField(default=3)),
                ('lec_schedule', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Lecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
    ]
