# Generated by Django 4.0.4 on 2024-03-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_mylectures_lecturestudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyLectures',
        ),
    ]
