name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # .env 파일 생성
    - name: Create .env file
      run:
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > final_project/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> final_project/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> final_project/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> final_project/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> final_project/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> final_project/.env

    - name: Run database migrations
      run: |
        python ./final_project/manage.py makemigrations --settings=final_project.settings.prod
        python ./final_project/manage.py migrate --settings=final_project.settings.prod

    - name: Run tests
      run: |
        python ./final_project/manage.py test--settings=final_project.settings.prod
