name: Django CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/app_build.yml'
      - 'final_project/**'
      - '!final_project/templates/**'
      - '!final_project/templates_local/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # aws configure
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

      # .env 파일 생성
    - name: Create .env file
      run: |
        cd final_project
        touch .env
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        cat .env

    - name: Install dependencies
      run: |
        cd final_project
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrate
      run: |
        cd final_project
        python manage.py makemigrations --settings=final_project.settings.prod
        python manage.py migrate --settings=final_project.settings.prod
    - name: Run tests
      run: |
        cd final_project
        ls -al
        python manage.py runserver 0.0.0.0:8000 --settings=final_project.settings.prod
