name: Django CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/app_build.yml'
      - 'final_project/**'
      - '!final_project/templates/**'
      - '!final_project/templates_local/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r final_project/requirements.txt

    - name: Set up MySQL
      run: |
        sudo apt-get update
        sudo apt-get install mysql-server -y
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234'; FLUSH PRIVILEGES;"
        sudo service mysql start

    - name: Run database migrations
      run: |
        cd final_project
        python manage.py makemigrations --settings=final_project.settings.local
        python manage.py migrate --settings=final_project.settings.local

    - name: Run tests
      run: |
        cd final_project
        python manage.py test runserver --settings=final_project.settings.local
