name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'final_project/**'
      - '!final_project/templates/**'
      - '!final_project/templates_local/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # .env 파일 생성
      - name: Create .env file
        run:
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > final_project/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> final_project/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> final_project/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> final_project/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> final_project/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> final_project/.env

      # Docker 이미지 빌드
      - name: Build Docker Image
        run:
          docker build -t jiwooum/sugangsite:latest -f ./final_project/Dockerfile .

      # Docker Hub 로그인
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Docker 이미지를 Docker Hub로 push
      - name: Push Docker Image to Docker Hub
        run:
          docker push jiwooum/sugangsite:latest

    # aws configure
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TR }}
          aws-region: ap-northeast-2

      # Kubernetes 구성 설정
      - name: Configure Kubernetes
        run: aws eks --region ap-northeast-2 update-kubeconfig --name sesac-eks-cls

      # Kubernetes에 배포
      - name: Deploy to Kubernetes
        run: |
          sudo kubectl apply -f /root/k8s/pod/alb.yaml